name: Build and Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
      - name: Build site
        run: hugo --minify
      - name: Markdown Lint
        uses: DavidAnson/markdownlint-cli2-action@v13
        with:
          globs: '**/*.md'
